const DATA=window.EPP_DATA;
const $=id=>document.getElementById(id);
const pad=n=>String(n).padStart(2,'0');
const toLocalInput=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
const fmt=d=>d?`${pad(d.getDate())}.${pad(d.getMonth()+1)}.${d.getFullYear()} ${pad(d.getHours())}:${pad(d.getMinutes())}`:'—';
const addH=(d,h)=>new Date(d.getTime()+h*3600000);
const state={method:'ETA',destination:'Hamburg',theme:'system',route:{speedLimit:true,opts:{}},encounter:{enabled:false,opts:{}},tides:{},berth:null};
const displayTargets={ETA:['Cuxhaven','Brunsbüttel','Bützfleth','Hamburg'],ETS:['Tonne Elbe','Cuxhaven','Brunsbüttel','Bützfleth']};
const targetPoint={ 'Tonne Elbe':'Tonne Elbe','Cuxhaven':'RadarTurm','Brunsbüttel':'Tonne_57','Bützfleth':'Tonne_99','Hamburg':'HaLo'};
const modules=[['grunddaten','Grunddaten'],['gezeiten','Gezeiten'],['fenster','Fenster'],['route','Route'],['hamburg','Hamburg'],['begegnung','Begegnung'],['printout','Print-out']];
const optDefs=[
 {id:'te-cux',label:'TN Elbe - Cux',from:'Tonne Elbe',to:'Kuba',fdw:true,time:false,level:1},
 {id:'cux-brb',label:'Cux - Brb',from:'Kuba',to:'Tonne_57',fdw:true,time:true,level:1},
 {id:'brb-hh',label:'Brb - HH',from:'Tonne_57',to:'HaLo',fdw:true,time:true,level:1},
 {id:'cuxhaven',label:'Cuxhaven',from:'Kuba',to:'Glameyer',fdw:true,time:false,level:2,parent:'cux-brb'},
 {id:'lw',label:'Lotsenwechsel',from:'Tonne_57',to:'Tonne_59',fdw:true,time:true,level:2,parent:'brb-hh'},
 {id:'dow',label:'DOW',from:'Tonne_99',to:'Tonne_101',fdw:true,time:false,level:2,parent:'brb-hh'},
 {id:'wedel',label:'Wedel',from:'Tonne_119',to:'Tonne_125',fdw:true,time:false,level:2,parent:'brb-hh'},
 {id:'delegation',label:'Delegations-Strecke',from:'Tonne_125',to:'HaLo',fdw:true,time:false,level:2,parent:'brb-hh'}
];
const routePoints=['TN Elbe','KuBa','Glameyer','TN 57','LOTSENWECHSEL','TN 59','DOW','TN 119','TN 125','HaLo'];
const pointAlias={'TN Elbe':'Tonne Elbe','KuBa':'Kuba','TN 57':'Tonne_57','TN 59':'Tonne_59','DOW':'Tonne_99','TN 119':'Tonne_119','TN 125':'Tonne_125','HaLo':'HaLo'};
const restrictions=[{name:'Altenbrucher Bogen',from:'Tonne_35',to:'Glameyer',max:90},{name:'Störbogen bis Wedel',from:'Tonne_75',to:'Tonne_121',max:92},{name:'Begegnungsbox',from:'Tonne_121',to:'Tonne_125',max:120}];
function init(){
 $('loginBtn').onclick=()=>{state.user=$('loginName').value||'Lotse';state.theme=$('themeChoice').value;applyTheme();$('login').hidden=true;$('app').hidden=false;$('userBadge').textContent=' · '+state.user; $('planner').value=state.user; renderAll();};
 $('themeToggle').onclick=()=>{state.theme=(document.body.dataset.theme==='dark')?'light':'dark';applyTheme();};
 const now=new Date(); $('planTime').value=toLocalInput(addH(now,4)); $('createdAt').value=toLocalInput(now); $('bEts').value=toLocalInput(addH(now,3));
 buildTabs(); buildTides(); buildOptions('routeOptions',state.route.opts); buildOptions('encounterOptions',state.encounter.opts); buildBerths(); bindInputs(document); updateMethod(); renderAll();
}
function applyTheme(){document.body.dataset.theme=state.theme==='system'?'':state.theme;}
function buildTabs(){ $('tabs').innerHTML=modules.map(([id,label])=>`<button data-tab="${id}">${label}</button>`).join(''); document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));}
function showTab(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('view-'+id).classList.add('active');document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));}
function bindInputs(root){root.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',renderAll));root.querySelectorAll('input[type=checkbox]').forEach(el=>el.addEventListener('change',renderAll));}
function updateMethod(){
 document.querySelectorAll('#methodButtons button').forEach(btn=>{btn.onclick=()=>{state.method=btn.dataset.method;document.querySelectorAll('#methodButtons button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');updateMethod();renderAll();};});
 const info={ETA:['ETA Tonne Elbe','Die angegebene Zeit bezieht sich auf die Ankunft an der Tonne Elbe. Es wird die Passage flussaufwärts bis zum gewählten Zielort berechnet.','TN Elbe\n  │\n  ▼\n Ziel'],ATA:['ATA Hamburg HaLo','Die angegebene Zeit bezieht sich auf die Ankunft in Hamburg (HaLo). Es wird rückwärts berechnet, wann das Schiff die Tonne Elbe passieren müsste, um das ATA zu erreichen.','TN Elbe\n  ▲\n  │\n HaLo'],ETS:['ETS Hamburg HaLo','Die angegebene Zeit bezieht sich auf die Abfahrt in Hamburg (HaLo). Es wird die Passage flussabwärts bis zum gewählten Zielort berechnet.','HaLo\n  │\n  ▼\n Ziel']}[state.method];
 $('methodInfo').innerHTML=`<strong>${info[0]}</strong><br>${info[1]}`; $('methodGraphic').textContent=info[2];
 $('timeLabel').firstChild.textContent=info[0]+' ';
 if(state.method==='ATA'){$('destinationWrap').style.display='none';state.destination='Hamburg';}
 else {$('destinationWrap').style.display='flex';$('destination').innerHTML=displayTargets[state.method].map(v=>`<option>${v}</option>`).join(''); if(!displayTargets[state.method].includes(state.destination))state.destination=displayTargets[state.method][0];$('destination').value=state.destination;}
}
function buildTides(){const places=['HEL','CUX','BRB','GLÜCK','HH']; const today=new Date(); $('tideTable').querySelector('tbody').innerHTML=places.map((p,i)=>{let base=addH(today, i*1.2); return `<tr><td>${p}</td><td><input type="datetime-local" value="${toLocalInput(addH(base,1))}"></td><td>${(p==='CUX'||p==='HH')?`<input type="datetime-local" value="${toLocalInput(addH(base,4))}">`:'—'}</td><td><input type="datetime-local" value="${toLocalInput(addH(base,13))}"></td><td>${(p==='CUX'||p==='HH')?`<input type="datetime-local" value="${toLocalInput(addH(base,16))}">`:'—'}</td><td><select><option>Vorherige Tide</option><option selected>Aktuelle Tide</option><option>Nächste Tide</option></select></td></tr>`}).join('');}
function buildBerths(){ $('berth').innerHTML=DATA.berths.map((b,i)=>`<option value="${i}">${b.berth}</option>`).join(''); state.berth=DATA.berths[0]; }
function speedOptions(){const fdw=+($('fdw')?.value||13);let out='';for(let v=6;v<=fdw+5+0.001;v+=0.5)out+=`<option value="${v.toFixed(1)}">${v.toFixed(1)} kn</option>`;return out;}
function timeOptions(){let out='';for(let v=0;v<=30;v+=5)out+=`<option value="${v}">${v} min</option>`;return out;}
function buildOptions(containerId,optState){$(containerId).innerHTML=optDefs.map(o=>{const st=optState[o.id]||{};return `<div class="option-card level-${o.level}"><h4>${o.label}</h4><small>${o.from} → ${o.to}</small><div class="inline-controls">${o.fdw?`<label class="switch"><input type="checkbox" data-opt="${o.id}" data-kind="fdw" ${st.fdw?'checked':''}> FdW aktiv</label><select data-opt="${o.id}" data-kind="fdwVal">${speedOptions()}</select>`:''}${o.time?`<label class="switch"><input type="checkbox" data-opt="${o.id}" data-kind="time" ${st.time?'checked':''}> Zeit aktiv</label><select data-opt="${o.id}" data-kind="timeVal">${timeOptions()}</select>`:''}</div></div>`}).join(''); $(containerId).querySelectorAll('select').forEach(el=>{const st=optState[el.dataset.opt]||{}; if(st[el.dataset.kind]) el.value=st[el.dataset.kind];}); $(containerId).querySelectorAll('input,select').forEach(el=>el.oninput=el.onchange=()=>{const id=el.dataset.opt,kind=el.dataset.kind; optState[id]=optState[id]||{}; if(el.type==='checkbox')optState[id][kind]=el.checked; else optState[id][kind]=el.value; renderAll();});}
function validate(){const cls=$('shipClass').value,L=+$('length').value,B=+$('beam').value,D=+$('draft').value,F=+$('fdw').value;let msgs=[];const maxL=cls==='Container'?400:370, maxB=cls==='Container'?62.5:63;if(L<=0||L>maxL)msgs.push(`🚨 Länge: max. ${maxL} m für ${cls}.`);if(B<=0||B>maxB)msgs.push(`🚨 Breite: max. ${maxB} m für ${cls}.`);if(D<=0||D>15.6)msgs.push('🚨 Tiefgang: max. 15,6 m.');if(F<6||F>25)msgs.push('🚨 FdW: zulässig 6–25 kn.');['wlCux','wlHH'].forEach(id=>{const v=+$(id).value;if(v<-25||v>5)msgs.push('🚨 Wasserstandsvorhersage: zulässig -25 bis +5 dm.');});$('validationBox').innerHTML=msgs.join('<br>')||'<span class="ok">✓ Schiffsdaten plausibel</span>';return msgs;}
function legHasPoint(l,point){return l.from===point||l.to===point;}
function rowSpeedLimit(row){if(row>=12&&row<=16)return 15;if(row>=17&&row<=20)return 14;if(row>=21&&row<=27)return 12;if(row>=28&&row<=30)return 10;return Infinity;}
function optionForLeg(l,optState){let val=null, delay=0; const active=o=>{let started=false, ok=false; for(const leg of DATA.route){if(leg.from===o.from)started=true;if(started && leg.row===l.row)ok=true;if(leg.to===o.to && started)break;} return ok;};
 for(const o of optDefs.filter(x=>x.level===1)){const st=optState[o.id]||{}; if(active(o)){ if(st.fdw) val=+(st.fdwVal||$('fdw').value); if(st.time) delay+=+(st.timeVal||0)/60; }}
 for(const o of optDefs.filter(x=>x.level===2)){const st=optState[o.id]||{}; if(active(o)){ if(st.fdw) val=+(st.fdwVal||$('fdw').value); if(st.time) delay+=+(st.timeVal||0)/60; }}
 return {speed:val,delay};}
function calculate(method=state.method,optState=state.route.opts,startTime=new Date($('planTime').value),fdw=+$('fdw').value){
 const forward=(method!=='ETS'); const points={}; const segments=[]; let t=new Date(startTime);
 if(method==='ATA'){ // planTime is desired HaLo; calculate backwards first, then return forward-like map
   const rev=[...DATA.route].reverse(); points['HaLo']=new Date(startTime);
   for(const l of rev){let sp=optionForLeg(l,optState).speed||fdw; if($('speedLimit')?.checked)sp=Math.min(sp,rowSpeedLimit(l.row)); let h=l.distance_nm/sp + optionForLeg(l,optState).delay; t=addH(t,-h); points[l.from]=new Date(t); segments.push({from:l.from,to:l.to,fdw:sp,current:null,fueg:sp,h});}
   return {points,segments:segments.reverse(),start:points['Tonne Elbe'],target:points[targetPoint[state.destination]||'HaLo']};
 }
 if(method==='ETS') {points['HaLo']=new Date(startTime); const rev=[...DATA.route].reverse(); for(const l of rev){let sp=optionForLeg(l,optState).speed||fdw;if($('speedLimit')?.checked)sp=Math.min(sp,rowSpeedLimit(l.row));let h=l.distance_nm/sp+optionForLeg(l,optState).delay;t=addH(t,h);points[l.from]=new Date(t);segments.push({from:l.to,to:l.from,fdw:sp,current:null,fueg:sp,h});} }
 else {points['Tonne Elbe']=new Date(startTime); for(const l of DATA.route){let sp=optionForLeg(l,optState).speed||fdw;if($('speedLimit')?.checked)sp=Math.min(sp,rowSpeedLimit(l.row));let tideOk=tidePlausible();let cur=tideOk?(0.2+((l.row%5)*0.25)):null;let fueg=tideOk?Math.max(3,sp+cur):sp;let h=l.distance_nm/fueg+optionForLeg(l,optState).delay;t=addH(t,h);points[l.to]=new Date(t);segments.push({from:l.from,to:l.to,fdw:sp,current:cur,fueg,h});} }
 return {points,segments,start:points['Tonne Elbe']||points['HaLo'],target:points[targetPoint[state.destination]||'HaLo']};
}
function tidePlausible(){return !document.querySelector('#tideTable select') || [...document.querySelectorAll('#tideTable select')].every(s=>s.value==='Aktuelle Tide');}
function routeChanges(optState=state.route.opts){return Object.values(optState).some(o=>o.fdw||o.time);}
function passageStatus(calc){const method=state.method, point=(method==='ETS')?'HaLo':'Tonne_13', eta=calc.points[point]; const wl=(method==='ETS')?+$('wlHH').value:+$('wlCux').value; const corr=+$('draft').value - wl/10; if(corr<=12.5)return {level:'ok',text:'tideunabhängig',point,eta,corr}; if(corr>15.6)return {level:'alarm',text:'Tmax / Passage nicht erlaubt',point,eta,corr}; const nw=new Date(eta); nw.setMinutes(0,0,0); const start=addH(nw,-0.5),end=addH(nw,0.75); const ok=eta>=start&&eta<=end;return {level:ok?'ok':'alarm',text:ok?'im Fenster':'außerhalb Fenster',point,eta,corr,start,end};}
function hamburgActive(){return (state.method==='ETA'&&state.destination==='Hamburg')||state.method==='ATA';}
function hamburgStatus(calc){if(!hamburgActive())return {level:'ok',text:'nicht relevant'};const b=DATA.berths[+$('berth').value]||DATA.berths[0];const corr=+$('draft').value - (+$('wlHH').value)/10;const eta=calc.points['HaLo'];let level='ok',text='Hamburg OK';if(corr>b.tjz){const h=eta.getHours(); if(h<2||h>22){level='alarm';text='Hamburg Fenster prüfen';} else text='Fenster berechnet';} if(b.conditionIds&&b.conditionIds.length>2){level=level==='alarm'?'alarm':'warn'; text=level==='warn'?'Hamburg Hinweise/Bedingungen':'Hamburg Alarm';}return {level,text,berth:b,corr,eta};}
function encounterCalc(calc){if(!$('encounterEnabled').checked)return null;const fdw=+$('bFdw').value, bStart=new Date($('bEts').value); const bcalc=calculate('ETS',state.encounter.opts,bStart,fdw); const aArr=DATA.route.map(l=>({point:l.to,time:calc.points[l.to]})); const bArr=DATA.route.map(l=>({point:l.from,time:bcalc.points[l.from]})); // find closest time crossing using cumulative distance
 let cum=0, positions={'Tonne Elbe':0}; for(const l of DATA.route){cum+=l.distance_nm;positions[l.to]=cum;} const total=cum;
 const samples=[]; const start=Math.max((calc.points['Tonne Elbe']||calc.points['HaLo']).getTime(), bStart.getTime()); const end=Math.min((calc.points['HaLo']||new Date()).getTime(), (bcalc.points['Tonne Elbe']||new Date(8640000000000000)).getTime());
 for(let t=start;t<=end;t+=5*60000){let pa=posAt(calc.points,positions,t,true), pb=posAt(bcalc.points,positions,t,false); if(pa!=null&&pb!=null)samples.push({t,pa,pb,d:Math.abs(pa-pb)});} if(!samples.length)return null; samples.sort((a,b)=>a.d-b.d); const m=samples[0]; const point=pointNear(positions,m.pa); const sum=+$('beam').value + +$('bBeam').value; const activeRestrictions=restrictions.filter(r=>sum>r.max); const hit=activeRestrictions.find(r=>m.pa>=positions[r.from]&&m.pa<=positions[r.to]); return {time:new Date(m.t),pos:m.pa,point,sum,activeRestrictions,hit};}
function posAt(points,positions,t,forward){const keys=Object.keys(points).filter(p=>positions[p]!=null).sort((a,b)=>points[a]-points[b]); for(let i=0;i<keys.length-1;i++){const a=keys[i],b=keys[i+1],ta=points[a].getTime(),tb=points[b].getTime(); if(t>=ta&&t<=tb){const f=(t-ta)/(tb-ta);return positions[a]+(positions[b]-positions[a])*f;}} return null;}
function pointNear(positions,pos){let best=null,bd=1e9; for(const [p,x] of Object.entries(positions)){const d=Math.abs(x-pos); if(d<bd){bd=d;best=p}} return best;}
function levelIcon(l){return l==='alarm'?'🚨':l==='warn'?'⚠':l==='info'?'ℹ':'✓';}
function overall(items){return items.some(i=>i.level==='alarm')?'alarm':items.some(i=>i.level==='warn')?'warn':items.some(i=>i.level==='info')?'info':'ok';}
function renderAll(){if(!$('app')||$('app').hidden)return; state.destination=$('destination').value||state.destination; validate(); buildOptions('routeOptions',state.route.opts); buildOptions('encounterOptions',state.encounter.opts); const calc=calculate(); const pass=passageStatus(calc); const ham=hamburgStatus(calc); const enc=encounterCalc(calc); const tide={level:tidePlausible()?'ok':'warn',text:tidePlausible()?'Tide OK':'Tidebezug prüfen'}; const route={level:routeChanges()?'info':'ok',text:routeChanges()?'Route angepasst':'Standardroute'}; const encounter={level:!$('encounterEnabled').checked?'ok':(enc?.hit?'alarm':'ok'),text:!$('encounterEnabled').checked?'nicht aktiv':(enc?.hit?'Begegnungsverbot':'Begegnung OK')}; renderStatus(calc,[tide,pass,route,ham,encounter]); renderTabs([tide,pass,route,ham,encounter]); renderPassage(pass); renderRouteMap(); renderHamburg(ham); renderEncounter(enc); renderPrint(calc,pass,ham,enc); $('encounterInputs').hidden=!$('encounterEnabled').checked; if($('speedLimit')) state.route.speedLimit=$('speedLimit').checked;}
function renderStatus(calc,items){const lvl=overall(items); const label=lvl==='alarm'?'KRITISCHE BEDINGUNGEN':lvl==='warn'?'PLANUNG PRÜFEN':'PLANUNG OK'; const target=calc.target; $('statusPanel').innerHTML=`<div><div class="status-main ${lvl}">${fmt(target)}</div><small>ETA / Ergebnis Zielort</small><br><strong class="${lvl}">${levelIcon(lvl)} ${label}</strong></div><div>${items.map(i=>`<span class="pill ${i.level}">${levelIcon(i.level)} ${i.text}</span>`).join('')}</div>`;}
function renderTabs(items){const status={gezeiten:items[0].level,fenster:items[1].level,route:items[2].level,hamburg:items[3].level,begegnung:items[4].level}; document.querySelectorAll('[data-tab]').forEach(b=>{const id=b.dataset.tab;b.dataset.status=status[id]||'ok'; if(id==='hamburg') b.style.display=hamburgActive()?'':'none'; if(id==='begegnung') b.style.display=$('encounterEnabled').checked?'':'none';});}
function renderPassage(p){$('passageWindowPanel').innerHTML=`<div class="pill ${p.level}">${levelIcon(p.level)} ${p.point==='HaLo'?'Seemannshöft / HaLo':'Bake C'}: ${p.text}</div><p><strong>Tfg korr.:</strong> ${p.corr.toFixed(2)} m</p>${p.start?`<p><strong>Fenster:</strong> ${fmt(p.start)} bis ${fmt(p.end)}</p>`:'<p>Kein Fenster zu berechnen.</p>'}`;}
function renderRouteMap(){let html=''; routePoints.forEach(p=>{if(p==='LOTSENWECHSEL')html+=`<div class="pilot-change">LOTSENWECHSEL</div>`; else html+=`<div class="river-point">● ${p}</div><div class="river-line"><small>${lineLabelAfter(p)}</small></div>`;}); $('routeMap').innerHTML=html;}
function lineLabelAfter(p){return {'TN Elbe':'TN Elbe - Cux','KuBa':'Cuxhaven','Glameyer':'Cux - Brb','TN 57':'','TN 59':'Brb - HH','DOW':'DOW','TN 119':'Wedel','TN 125':'Delegations-Strecke'}[p]||'';}
function renderHamburg(h){if(!hamburgActive())return; $('hhWaterDisplay').value=$('wlHH').value+' dm'; $('correctedDraftHH').value=h.corr.toFixed(2)+' m'; $('tjzPanel').innerHTML=`<p><strong>TJZ am Liegeplatz:</strong> ${h.berth.tjz.toFixed(2)} m</p><p><strong>Einlauffenster:</strong> ${h.corr<=h.berth.tjz?'Kann zu jeder Zeit kommen.':'Fenster berechnet – Details in Anlaufbedingungen.'}</p><p class="${h.level}">${levelIcon(h.level)} ${h.text}</p>`; renderHamburgCurve(h); $('hamburgLegend').innerHTML=`<div class="pill ${h.level}">${levelIcon(h.level)} ${h.text}</div><p><strong>Bedingungen:</strong> ${(h.berth.conditionIds||[]).join(', ')||'keine'}</p><p><strong>Info:</strong> ${h.berth.infoId||'—'}</p>`;}
function renderHamburgCurve(h){$('hamburgCurve').innerHTML=`<svg viewBox="0 0 1000 220" preserveAspectRatio="none"><path d="M0 160 C120 210 200 25 320 95 S520 185 640 75 S840 35 1000 150" fill="none" stroke="currentColor" stroke-width="5" opacity=".55"/><line x1="650" y1="20" x2="650" y2="205" stroke="var(--warn)" stroke-width="4"/><text x="660" y="42" fill="currentColor">ETA HaLo</text><rect x="430" y="145" width="250" height="22" rx="8" fill="var(--ok)" opacity=".25"/><text x="445" y="140" fill="currentColor">TJZ-Fenster</text></svg>`;}
function renderEncounter(enc){if(!$('encounterEnabled').checked)return; const sum=+$('beam').value+ +$('bBeam').value; const active=restrictions.filter(r=>sum>r.max); let html='<div class="encounter-line"><div class="shipA">Schiff A ↓</div></div>'; routePoints.forEach(p=>{if(p==='LOTSENWECHSEL') html+=`<div class="pilot-change">LOTSENWECHSEL</div>`; else {html+=`<div class="encounter-line"><div class="encounter-node">${p}</div>`; if(enc&&pointNearObject(p,enc.point))html+=`<div class="meeting">● ${pad(enc.time.getHours())}:${pad(enc.time.getMinutes())}</div>`; active.filter(r=>restrictionNear(p,r)).forEach(r=>html+=`<div class="restriction">${r.name} · ${sum.toFixed(1)} m${enc?.hit?.name===r.name?' · 🚨 Sperrbedingung greift':''}</div>`); html+='</div>';}}); html+='<div class="encounter-line"><div class="shipB">Schiff B ↑</div></div>'; $('encounterMap').innerHTML=html;}
function pointNearObject(label,point){return label==='DOW'&&point==='Tonne_99'||label==='TN 119'&&point==='Tonne_119'||label==='Glameyer'&&point==='Glameyer'||label==='HaLo'&&point==='HaLo'||label==='TN 57'&&point==='Tonne_57'||label==='TN Elbe'&&point==='Tonne Elbe';}
function restrictionNear(label,r){return (r.name==='Altenbrucher Bogen'&&label==='Glameyer')||(r.name==='Störbogen bis Wedel'&&label==='DOW')||(r.name==='Begegnungsbox'&&label==='TN 125');}
function renderPrint(calc,p,h,enc){const activeOpts=optDefs.filter(o=>{const st=state.route.opts[o.id]||{};return st.fdw||st.time}).map(o=>o.label).join(', ')||'Standardroute'; const display=['Tonne Elbe','Tonne_13','Kuba','Glameyer','Tonne_57','Tonne_59','Tonne_99','Tonne_119','Tonne_125','HaLo']; $('printPreview').innerHTML=`<h3>ELBE PASSAGE PLAN</h3><p><strong>Planung:</strong> ${fmt(new Date($('createdAt').value))} · <strong>Bearbeiter:</strong> ${$('planner').value}</p><p><strong>Schiff:</strong> ${$('shipName').value||'—'} · ${$('shipClass').value} · L ${$('length').value} m · B ${$('beam').value} m · Tfg ${$('draft').value} m · FdW ${$('fdw').value} kn</p><p><strong>Elbe Speed Limit:</strong> ${$('speedLimit').checked?'aktiviert':'deaktiviert'} · <strong>Stellschrauben:</strong> ${activeOpts}</p><p><strong>Passagefenster:</strong> ${p.text} · Tfg korr. ${p.corr.toFixed(2)} m</p>${hamburgActive()?`<p><strong>Hamburg:</strong> ${h.berth.berth} · TJZ ${h.berth.tjz.toFixed(2)} m · ${h.text}</p>`:''}${enc?`<p><strong>Begegnung:</strong> ${fmt(enc.time)} · ${enc.hit?'🚨 Begegnungsverbot':'✓ zulässig'} · Breite ${enc.sum.toFixed(1)} m</p>`:''}<table><thead><tr><th>Punkt</th><th>ETA</th></tr></thead><tbody>${display.map(pt=>`<tr><td>${pt.replace('Tonne_13','Bake C').replace('Tonne_57','Brunsbüttel TN57').replace('Tonne_59','Brunsbüttel TN59').replace('Tonne_99','DOW').replace('Tonne_119','Tonne 117').replace('Tonne_125','Landesgrenze')}</td><td>${fmt(calc.points[pt])}</td></tr>`).join('')}</tbody></table>`;}
$('printBtn').onclick=()=>window.print();
init();
